-- Seed core vocabulary across supported languages.
insert into public.words (id, word, language_code, translation, romanization, part_of_speech)
values
  (gen_random_uuid(), 'sperare', 'it', 'to hope', null, 'verb'),
  (gen_random_uuid(), 'nazione', 'it', 'nation', null, 'noun'),
  (gen_random_uuid(), 'animale', 'it', 'animal', null, 'noun'),
  (gen_random_uuid(), 'importante', 'it', 'important', null, 'adjective'),
  (gen_random_uuid(), 'differente', 'it', 'different', null, 'adjective'),
  (gen_random_uuid(), 'amore', 'it', 'love', null, 'noun'),
  (gen_random_uuid(), 'tempo', 'it', 'time', null, 'noun'),
  (gen_random_uuid(), 'vita', 'it', 'life', null, 'noun'),
  (gen_random_uuid(), 'casa', 'it', 'house', null, 'noun'),
  (gen_random_uuid(), 'lavoro', 'it', 'work', null, 'noun'),
  (gen_random_uuid(), 'famiglia', 'it', 'family', null, 'noun'),
  (gen_random_uuid(), 'musica', 'it', 'music', null, 'noun'),
  (gen_random_uuid(), 'storia', 'it', 'history', null, 'noun'),
  (gen_random_uuid(), 'problema', 'it', 'problem', null, 'noun'),
  (gen_random_uuid(), 'programma', 'it', 'program', null, 'noun'),
  (gen_random_uuid(), 'universita', 'it', 'university', null, 'noun'),
  (gen_random_uuid(), 'possibile', 'it', 'possible', null, 'adjective'),
  (gen_random_uuid(), 'naturale', 'it', 'natural', null, 'adjective'),
  (gen_random_uuid(), 'centrale', 'it', 'central', null, 'adjective'),
  (gen_random_uuid(), 'moderno', 'it', 'modern', null, 'adjective'),
  (gen_random_uuid(), 'creare', 'it', 'to create', null, 'verb'),
  (gen_random_uuid(), 'usare', 'it', 'to use', null, 'verb'),
  (gen_random_uuid(), 'parlare', 'it', 'to speak', null, 'verb'),
  (gen_random_uuid(), 'studiare', 'it', 'to study', null, 'verb'),
  (gen_random_uuid(), 'arrivare', 'it', 'to arrive', null, 'verb'),
  (gen_random_uuid(), 'partire', 'it', 'to leave', null, 'verb'),
  (gen_random_uuid(), 'aiutare', 'it', 'to help', null, 'verb'),
  (gen_random_uuid(), 'pensare', 'it', 'to think', null, 'verb'),
  (gen_random_uuid(), 'ricordare', 'it', 'to remember', null, 'verb'),
  (gen_random_uuid(), 'cambiare', 'it', 'to change', null, 'verb'),
  (gen_random_uuid(), 'strada', 'it', 'street', null, 'noun'),
  (gen_random_uuid(), 'citta', 'it', 'city', null, 'noun'),
  (gen_random_uuid(), 'scuola', 'it', 'school', null, 'noun'),
  (gen_random_uuid(), 'libro', 'it', 'book', null, 'noun'),
  (gen_random_uuid(), 'acqua', 'it', 'water', null, 'noun'),
  (gen_random_uuid(), 'fuoco', 'it', 'fire', null, 'noun'),
  (gen_random_uuid(), 'amico', 'it', 'friend', null, 'noun'),
  (gen_random_uuid(), 'donna', 'it', 'woman', null, 'noun'),
  (gen_random_uuid(), 'uomo', 'it', 'man', null, 'noun'),
  (gen_random_uuid(), 'giorno', 'it', 'day', null, 'noun'),
  (gen_random_uuid(), 'notte', 'it', 'night', null, 'noun'),
  (gen_random_uuid(), 'grande', 'it', 'big', null, 'adjective'),
  (gen_random_uuid(), 'piccolo', 'it', 'small', null, 'adjective'),
  (gen_random_uuid(), 'felice', 'it', 'happy', null, 'adjective'),
  (gen_random_uuid(), 'triste', 'it', 'sad', null, 'adjective'),
  (gen_random_uuid(), 'veloce', 'it', 'fast', null, 'adjective'),
  (gen_random_uuid(), 'lento', 'it', 'slow', null, 'adjective'),
  (gen_random_uuid(), 'chiaro', 'it', 'clear', null, 'adjective'),
  (gen_random_uuid(), 'scuro', 'it', 'dark', null, 'adjective'),
  (gen_random_uuid(), 'utile', 'it', 'useful', null, 'adjective'),

  (gen_random_uuid(), 'esperar', 'es', 'to hope', null, 'verb'),
  (gen_random_uuid(), 'nacion', 'es', 'nation', null, 'noun'),
  (gen_random_uuid(), 'animal', 'es', 'animal', null, 'noun'),
  (gen_random_uuid(), 'importante', 'es', 'important', null, 'adjective'),
  (gen_random_uuid(), 'diferente', 'es', 'different', null, 'adjective'),
  (gen_random_uuid(), 'amor', 'es', 'love', null, 'noun'),
  (gen_random_uuid(), 'tiempo', 'es', 'time', null, 'noun'),
  (gen_random_uuid(), 'vida', 'es', 'life', null, 'noun'),
  (gen_random_uuid(), 'casa', 'es', 'house', null, 'noun'),
  (gen_random_uuid(), 'trabajo', 'es', 'work', null, 'noun'),
  (gen_random_uuid(), 'familia', 'es', 'family', null, 'noun'),
  (gen_random_uuid(), 'musica', 'es', 'music', null, 'noun'),
  (gen_random_uuid(), 'historia', 'es', 'history', null, 'noun'),
  (gen_random_uuid(), 'problema', 'es', 'problem', null, 'noun'),
  (gen_random_uuid(), 'programa', 'es', 'program', null, 'noun'),
  (gen_random_uuid(), 'universidad', 'es', 'university', null, 'noun'),
  (gen_random_uuid(), 'posible', 'es', 'possible', null, 'adjective'),
  (gen_random_uuid(), 'natural', 'es', 'natural', null, 'adjective'),
  (gen_random_uuid(), 'central', 'es', 'central', null, 'adjective'),
  (gen_random_uuid(), 'moderno', 'es', 'modern', null, 'adjective'),
  (gen_random_uuid(), 'crear', 'es', 'to create', null, 'verb'),
  (gen_random_uuid(), 'usar', 'es', 'to use', null, 'verb'),
  (gen_random_uuid(), 'hablar', 'es', 'to speak', null, 'verb'),
  (gen_random_uuid(), 'estudiar', 'es', 'to study', null, 'verb'),
  (gen_random_uuid(), 'llegar', 'es', 'to arrive', null, 'verb'),
  (gen_random_uuid(), 'salir', 'es', 'to leave', null, 'verb'),
  (gen_random_uuid(), 'ayudar', 'es', 'to help', null, 'verb'),
  (gen_random_uuid(), 'pensar', 'es', 'to think', null, 'verb'),
  (gen_random_uuid(), 'recordar', 'es', 'to remember', null, 'verb'),
  (gen_random_uuid(), 'cambiar', 'es', 'to change', null, 'verb'),
  (gen_random_uuid(), 'calle', 'es', 'street', null, 'noun'),
  (gen_random_uuid(), 'ciudad', 'es', 'city', null, 'noun'),
  (gen_random_uuid(), 'escuela', 'es', 'school', null, 'noun'),
  (gen_random_uuid(), 'libro', 'es', 'book', null, 'noun'),
  (gen_random_uuid(), 'agua', 'es', 'water', null, 'noun'),
  (gen_random_uuid(), 'fuego', 'es', 'fire', null, 'noun'),
  (gen_random_uuid(), 'amigo', 'es', 'friend', null, 'noun'),
  (gen_random_uuid(), 'mujer', 'es', 'woman', null, 'noun'),
  (gen_random_uuid(), 'hombre', 'es', 'man', null, 'noun'),
  (gen_random_uuid(), 'dia', 'es', 'day', null, 'noun'),
  (gen_random_uuid(), 'noche', 'es', 'night', null, 'noun'),
  (gen_random_uuid(), 'grande', 'es', 'big', null, 'adjective'),
  (gen_random_uuid(), 'pequeno', 'es', 'small', null, 'adjective'),
  (gen_random_uuid(), 'feliz', 'es', 'happy', null, 'adjective'),
  (gen_random_uuid(), 'triste', 'es', 'sad', null, 'adjective'),
  (gen_random_uuid(), 'rapido', 'es', 'fast', null, 'adjective'),
  (gen_random_uuid(), 'lento', 'es', 'slow', null, 'adjective'),
  (gen_random_uuid(), 'claro', 'es', 'clear', null, 'adjective'),
  (gen_random_uuid(), 'oscuro', 'es', 'dark', null, 'adjective'),
  (gen_random_uuid(), 'util', 'es', 'useful', null, 'adjective'),

  (gen_random_uuid(), 'esperer', 'fr', 'to hope', null, 'verb'),
  (gen_random_uuid(), 'nation', 'fr', 'nation', null, 'noun'),
  (gen_random_uuid(), 'animal', 'fr', 'animal', null, 'noun'),
  (gen_random_uuid(), 'important', 'fr', 'important', null, 'adjective'),
  (gen_random_uuid(), 'different', 'fr', 'different', null, 'adjective'),
  (gen_random_uuid(), 'amour', 'fr', 'love', null, 'noun'),
  (gen_random_uuid(), 'temps', 'fr', 'time', null, 'noun'),
  (gen_random_uuid(), 'vie', 'fr', 'life', null, 'noun'),
  (gen_random_uuid(), 'maison', 'fr', 'house', null, 'noun'),
  (gen_random_uuid(), 'travail', 'fr', 'work', null, 'noun'),
  (gen_random_uuid(), 'famille', 'fr', 'family', null, 'noun'),
  (gen_random_uuid(), 'musique', 'fr', 'music', null, 'noun'),
  (gen_random_uuid(), 'histoire', 'fr', 'history', null, 'noun'),
  (gen_random_uuid(), 'probleme', 'fr', 'problem', null, 'noun'),
  (gen_random_uuid(), 'programme', 'fr', 'program', null, 'noun'),
  (gen_random_uuid(), 'universite', 'fr', 'university', null, 'noun'),
  (gen_random_uuid(), 'possible', 'fr', 'possible', null, 'adjective'),
  (gen_random_uuid(), 'naturel', 'fr', 'natural', null, 'adjective'),
  (gen_random_uuid(), 'central', 'fr', 'central', null, 'adjective'),
  (gen_random_uuid(), 'moderne', 'fr', 'modern', null, 'adjective'),
  (gen_random_uuid(), 'creer', 'fr', 'to create', null, 'verb'),
  (gen_random_uuid(), 'utiliser', 'fr', 'to use', null, 'verb'),
  (gen_random_uuid(), 'parler', 'fr', 'to speak', null, 'verb'),
  (gen_random_uuid(), 'etudier', 'fr', 'to study', null, 'verb'),
  (gen_random_uuid(), 'arriver', 'fr', 'to arrive', null, 'verb'),
  (gen_random_uuid(), 'partir', 'fr', 'to leave', null, 'verb'),
  (gen_random_uuid(), 'aider', 'fr', 'to help', null, 'verb'),
  (gen_random_uuid(), 'penser', 'fr', 'to think', null, 'verb'),
  (gen_random_uuid(), 'changer', 'fr', 'to change', null, 'verb'),
  (gen_random_uuid(), 'ville', 'fr', 'city', null, 'noun');

-- Pre-seed a few Spanish-source hints for Italian words.
insert into public.hints (id, word_id, source_language_code, hint_text, hint_type, confidence)
values
  (
    gen_random_uuid(),
    (select id from public.words where language_code = 'it' and word = 'sperare' limit 1),
    'es',
    'Italian "sperare" is close to Spanish "esperar" (to hope).',
    'cognate',
    0.98
  ),
  (
    gen_random_uuid(),
    (select id from public.words where language_code = 'it' and word = 'nazione' limit 1),
    'es',
    'Italian "nazione" aligns with Spanish "nacion" (nation).',
    'cognate',
    0.97
  ),
  (
    gen_random_uuid(),
    (select id from public.words where language_code = 'it' and word = 'importante' limit 1),
    'es',
    'Italian "importante" matches Spanish "importante" exactly.',
    'structural_parallel',
    0.99
  );
